name: example-environment
channels:
  - conda-forge
dependencies:
  - python==3.6.* 
  - plotly==3.7.*
  - pip
  - pip:
    - rpy2==2.9.*
    - tzlocal
    - simplegeneric
    - -r requirements.txt
    
