name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy==1.16.*
  - matplotlib==3.*
  - seaborn==0.8.1
  - pandas
  - cufflinks
  - python
  - pip
  - pip:
    - cufflinks==0.12.1
    - rpy2
